### ISSUE TITLE
KeyError: 'zero123-unified-guidance-cache'

### ISSUE THREAD

**Issue by altava-sgp** [Adamdad/hash3D#3]
I run this command.
```shell
python launch.py --config configs/stable-zero123_hash3d.yaml --train --gpu 0 data.image_path=load/images/dog1_rgba.png
```
I got this error.
```shell
$ python launch.py --config configs/stable-zero123_hash3d.yaml --train --gpu 0 data.image_path=load/images/dog1_rgba.png
Global seed set to 0
find:  single-image-datamodule
find:  zero123-system
find:  implicit-volume
find:  diffuse-with-point-light-material
find:  solid-color-background
find:  nerf-volume-renderer
[INFO] ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] single image dataset: load image load/images/dog1_rgba.png torch.Size([1, 128, 128, 3])
[INFO] single image dataset: load image load/images/dog1_rgba.png torch.Size([1, 128, 128, 3])
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[INFO] 
  | Name       | Type                          | Params
-------------------------------------------------------------
0 | geometry   | ImplicitVolume                | 12.6 M
1 | material   | DiffuseWithPointLightMaterial | 0     
2 | background | SolidColorBackground          | 0     
3 | renderer   | NeRFVolumeRenderer            | 0     
-------------------------------------------------------------
12.6 M    Trainable params
0         Non-trainable params
12.6 M    Total params
50.450    Total estimated model params size (MB)
[INFO] Validation results will be saved to outputs/zero123-sai-hash3d/[64, 128, 256]_dog1_rgba.png@20240418-085259/save
find:  zero123-unified-guidance-cache
Traceback (most recent call last):
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/launch.py", line 244, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _run
    call._call_lightning_module_hook(self, "on_fit_start")
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/systems/zero123.py", line 40, in on_fit_start
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/__init__.py", line 33, in find
    return __modules__[name]
KeyError: 'zero123-unified-guidance-cache'
```

What's the problem ?

**Comment by Adamdad** [comment]
Hello, can you check how to you set the path to your threestudio package. I am sure that the class of `zero123-unified-guidance-cache` is inside the code but it seems that you cannot access this class. Can you please check?

https://github.com/Adamdad/hash3D/blob/d705863c675bc644e84610b289e5f4eeb75b8aa3/threestudio-hash3d/threestudio/models/guidance/zero123_unified_guidance_cache.py#L34

**Comment by altava-sgp** [comment]
@Adamdad The structure of folders and files is here.
![image](https://github.com/Adamdad/hash3D/assets/133635323/703ca925-9ee7-4893-a6a9-d898c9e33584)

**Comment by Adamdad** [comment]
Can you run the code again, and set `export PYTHONPATH="$PWD"` before running your script?

**Comment by altava-sgp** [comment]
It pauses for a little time after this...
```shell
$ pwd
/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d
$ 
$ export PYTHONPATH="$PWD"
$ 
$ python launch.py --config configs/stable-zero123_hash3d.yaml --train --gpu 0 data.image_path=load/images/dog1_rgba.png
Global seed set to 0
find:  single-image-datamodule
find:  zero123-system
find:  implicit-volume
find:  diffuse-with-point-light-material
find:  solid-color-background
find:  nerf-volume-renderer
[INFO] ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] single image dataset: load image load/images/dog1_rgba.png torch.Size([1, 128, 128, 3])
[INFO] single image dataset: load image load/images/dog1_rgba.png torch.Size([1, 128, 128, 3])
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
```

I am waiting...

**Comment by altava-sgp** [comment]
I run command in docker terminal.
![image](https://github.com/Adamdad/hash3D/assets/133635323/581dc207-0f78-4c9c-b364-3b1469dcb20f)

**Comment by altava-sgp** [comment]
Eventually I got this error again.
![image](https://github.com/Adamdad/hash3D/assets/133635323/eb336d27-2e1b-4710-a3ea-598109949b6b)

```shell
$ pwd
/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d
$ 
$ export PYTHONPATH="$PWD"
$ 
$ python launch.py --config configs/stable-zero123_hash3d.yaml --train --gpu 0 data.image_path=load/images/dog1_rgba.png
Global seed set to 0
find:  single-image-datamodule
find:  zero123-system
find:  implicit-volume
find:  diffuse-with-point-light-material
find:  solid-color-background
find:  nerf-volume-renderer
[INFO] ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] single image dataset: load image load/images/dog1_rgba.png torch.Size([1, 128, 128, 3])
[INFO] single image dataset: load image load/images/dog1_rgba.png torch.Size([1, 128, 128, 3])
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[INFO] 
  | Name       | Type                          | Params
-------------------------------------------------------------
0 | geometry   | ImplicitVolume                | 12.6 M
1 | material   | DiffuseWithPointLightMaterial | 0     
2 | background | SolidColorBackground          | 0     
3 | renderer   | NeRFVolumeRenderer            | 0     
-------------------------------------------------------------
12.6 M    Trainable params
0         Non-trainable params
12.6 M    Total params
50.450    Total estimated model params size (MB)
[INFO] Validation results will be saved to outputs/zero123-sai-hash3d/[64, 128, 256]_dog1_rgba.png@20240418-092826/save
find:  zero123-unified-guidance-cache
Traceback (most recent call last):
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/launch.py", line 244, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _run
    call._call_lightning_module_hook(self, "on_fit_start")
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/systems/zero123.py", line 40, in on_fit_start
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/__init__.py", line 33, in find
    return __modules__[name]
KeyError: 'zero123-unified-guidance-cache'
```

**Comment by Adamdad** [comment]
can git pull again? I just push one line of code 

https://github.com/Adamdad/hash3D/blob/ea45d58b394ff8e822cb0e98dde82d16193f458a/threestudio-hash3d/threestudio/models/guidance/__init__.py#L01-L12

**Comment by altava-sgp** [comment]
I got this error.
```shell
$ pwd
/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d
$ 
$ python launch.py --config configs/stable-zero123_hash3d.yaml --train --gpu 0 data.image_path=load/images/dog1_rgba.png
Traceback (most recent call last):
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/launch.py", line 135, in main
    import threestudio
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/__init__.py", line 55, in <module>
    from . import data, models, systems
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/models/__init__.py", line 1, in <module>
    from . import (
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/models/guidance/__init__.py", line 1, in <module>
    from . import (
  File "/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/models/guidance/zero123_unified_guidance_cache.py", line 31, in <module>
    from threestudio.utils.hash_table import GridBasedHashTable, GridBasedHashTable_Sim, AdaptiveGridBasedHashTable, GridBasedHashTable_Key
ImportError: cannot import name 'GridBasedHashTable_Key' from 'threestudio.utils.hash_table' (/home/dreamer/threestudio/custom/hash3D/threestudio-hash3d/threestudio/utils/hash_table.py)
```

**Comment by Adamdad** [comment]
Sorry, just remove this. Can pull again. `GridBasedHashTable_Key` is an ablated version of my full method.

**Comment by altava-sgp** [comment]
It is working!
![image](https://github.com/Adamdad/hash3D/assets/133635323/fd9ee417-cc22-4cbf-b305-d2d769a00fac)

Let's see what will happen

**Comment by altava-sgp** [comment]
I got it !

![image](https://github.com/Adamdad/hash3D/assets/133635323/b08944c9-3575-4f8c-80a3-3e922dbfab6b)
![image](https://github.com/Adamdad/hash3D/assets/133635323/7fdfbedf-958d-41f3-990d-439e7a7b020a)

https://github.com/Adamdad/hash3D/assets/133635323/e75689e6-f102-42f6-998f-1f4e1c95eeda

**Comment by altava-sgp** [comment]
So can I use this ckpt file of this to proceed next steps ?
![image](https://github.com/Adamdad/hash3D/assets/133635323/7cf79fb4-4408-44be-9ddf-9dcf0ab4268e)

**Comment by Adamdad** [comment]
Yes, threestudio can help you to convert this ckpt to mesh .obj and can be applied to other applications.

**Comment by altava-sgp** [comment]
@Adamdad Are you in threestudio discord server ?

**Comment by Adamdad** [comment]
Can you give a star on the project? Thank you so much!
